version: "3.9"

services:
  gpt4free-ts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt4free-ts
    image: gpt4free-ts:latest
    ports:
      - "3000:3000"
    restart: always
    cap_add:
      - "SYS_ADMIN"
    environment:
      #      - TZ=Asia/Shanghai
      - http_proxy=${http_proxy}
      - https_proxy=${http_proxy}
      - rapid_api_key=${rapid_api_key}
